#
# Build the Handbook with just the content from this chapter.
#
# The FreeBSD Simplified Chinese Project
# Original Revision: r43258
#
# $FreeBSD$
#

CHAPTERS= 	virtualization/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
