#
# Build the Handbook with just the content from this chapter.
#
# Original Revision: r43258
# $FreeBSD$
#

CHAPTERS= 	x11/chapter.xml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
